# Generated by Django 4.2.14 on 2024-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('canceled', 'Canceled')], db_index=True, default='sent', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('deleted', 'Deleted')], db_index=True, default='new', max_length=12, verbose_name='Status'),
        ),
    ]
