# Generated by Django 4.2.14 on 2024-07-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_interest_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='message',
        ),
    ]
